= streams_halfmill

Tesing 1/2 million records on streams by constraining CPUs and memory.  Records are sized at 650000 bytes. 

* Installation based on streams 1.3/7.5. See product https://access.redhat.com/documentation/en-us/red_hat_amq/7.5/html/using_amq_streams_on_openshift/index[documentation] for more detail  
* Uses 3 kafka nodes
* Uses 3 replicas
* Uses 40 partitions
* Uses 2 cpus and 4Gi of memory.  See broker https://github.com/rediverson/streams_halfmill/blob/master/examples/kafka/kafka-persistent.yaml[config] for more details.


== Install cluster operator

Review the installation https://access.redhat.com/documentation/en-us/red_hat_amq/7.5/html/using_amq_streams_on_openshift/getting-started-str#downloads-str[instructions] first.

IMPORTANT: Installation requires a user with cluster admin priviledges

After logging into openshift via the cli create a new project
----
oc new-project kafka
----

Create the cluster operator in the kafka project/namespace
----
oc apply -f install/cluster-operator -n kafka
oc apply -f examples/templates/cluster-operator -n kafka
----

== Install and configure kafka cluster

Create the kafka cluster in the name space
----
oc apply -f examples/kafka/kafka-persistent.yaml
----

Create a topic (make sure the 3 zookeeper and 3 kafka pods are started)
----
oc apply -f examples/topic/kafka-topic.yaml
----

== Running within container

Download your service account from https://access.redhat.com/terms-based-registry/ as an OpenShift secret and reference it below.  Note certain values below must be changed to me your environment
----
oc create -f my-service-account-pull-secret.yaml
oc secrets link builder my-service-account-pull-secret
oc new-app --name perf-client https://github.com/rediverson/streams-perf.git
oc get pods
oc rsh perf-client-1-t7tn7
cd /tmp/home/streams-perf/client/bin
----

=== Modify Configuration
Modify the `producer.properties` to meet your environment configuration
Use the fully qualified service addresses within openshift. Example below:
----
bootstrap.servers=https://my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
----
Remove all ssl settings

=== Execute the producer performance test

Note: You must have kafka installed locally and its `bin` directory is included in the `PATH` environment variable

----
./kafka-producer-perf-test.sh --producer.config producer.properties --throughput -1 --num-records 500000 --record-size 650000 --topic my-topic

----

== Delete topics and clusters
Delete topic, user and cluster with sample below
----
oc delete kafkauser my-user
oc delete kafkatopic my-topic
oc delete kafka my-cluster
----



